name: codeql_scan
on:
  workflow_dispatch:
jobs:
  codeql-scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
        
     # Initialize the CodeQL tools for scanning
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java
          queries: security-and-quality
          source-root: ./src
       
      - name: Java Build
        run: mvn clean compile --file pom.xml
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          ram: 2048
          threads: 1
